#' Extract cluster enrichment table
#' @param scMuffinList scMuffinList object
#' @param partition_id id of the partition to be used
#' @param type "GSEA" or "ORA"
#' @param quantity possible values are as follows. GSEA: es, enrichment score; p_val empirical p-value; adj_p_val, FDR (BH); nes normalized enrichment score; FDRq empirical FDR. ORA: wbd (white balls drawn), number of cells with the value of interest in the cluster; exp expected number of cells with the value of interest in the cluster; er, enrichment ratio; p, hypergeometric test p-value; p_adj, BH FDR
#' @param feature_id name of the features that will be considered. Must be any of `colnames(scMuffinList$cluster_data$[[parition_id]]$GSEA$gs_table)` or `names(scMuffinList$cluster_data$[[parition_id]]$ORA)`
#' @description Extract cluster enrichment table with the desired quantity from the results generated by means of [assess_cluster_enrichment()]
#' @return A cluster enrichment table with the desired quantity
#' @importFrom stats setNames
#' @export

extract_cluster_enrichment_table <- function(scMuffinList, partition_id=NULL, type=NULL, quantity=NULL, feature_id=NULL){
  
  if(is.null(quantity)){
    stop("quantity can not be null.\n")
  }
  if(type == "GSEA" & !is.null(scMuffinList$cluster_data[[partition_id]]$GSEA)){
    
    ans <- scMuffinList$cluster_data[[partition_id]]$GSEA$gs_table
    if(!is.null(feature_id)){
      ans <- ans[names(ans) %in% feature_id]
    }
    ans <- do.call(cbind, lapply(ans, function(x) array(x[, colnames(x)==quantity], dimnames = list(x$id))))
  }
  
  
  if(type == "ORA" & !is.null(scMuffinList$cluster_data[[partition_id]]$ORA)){
    
    ans <- scMuffinList$cluster_data[[partition_id]]$ORA
    if(!is.null(feature_id)){
      ans <- ans[names(ans) %in% feature_id]
    }
    ans <- lapply(ans, function(ans_i) do.call(cbind, lapply(ans_i, function(x) setNames(x[, colnames(x)==quantity], x$id))))
                  
  }

  return(ans)
  
}